name: Deploy

on:
  push:
    branches:
      - master

jobs:
  initial:
    runs-on: ubuntu-latest
    name: Initial Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # You can add more steps if needed

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers
    needs: initial
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@1.2.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
